import com.esg.utils.PodTemplates

slaveTemplates = new PodTemplates()

pipeline {
  agent {
    kubernetes {
      yamlFile 'Kube-Test-From-YAML/KubernetesPod.yaml'
    }
  }
  stages {
    stage('Run maven') {
      steps {
        sh "echo ${slaveTemplates}"
//        sh 'set'
//        sh "echo OUTSIDE_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}"
//        container('maven') {
//          sh 'echo MAVEN_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
//          sh 'mvn -version'
//        }
//        container('busybox') {
//          sh 'echo BUSYBOX_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
//          sh '/bin/busybox'
//        }
      }
    }
  }
}
